name: Stable cargo build for Geyser plugin

on:
  pull_request:
  push:
    branches: [dev, master]

jobs:
  check:
    name: cargo +stable build rabbitmq-geyser
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: cargo, rustc
          profile: minimal

      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib -pholaplex-indexer-rabbitmq-geyser --profile=release-lite

